# Generated by Django 2.1.1 on 2018-10-01 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181001_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenzja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(default='')),
                ('gwiazdki', models.IntegerField(default=5)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Film')),
            ],
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (4, 'Komedia'), (3, 'Drama'), (2, 'Sci-fi'), (1, 'Horror')], default=0),
        ),
    ]
